### ISSUE TITLE
Can't clone black eye

### ISSUE THREAD

**Issue by MarcelGumlich** [Zack-sys/Blackeye#1]
$ sudo git clone https://github.com/thelinuxchoice/blackeye
Cloning into ´blackeye´...
Username for ´https://github.com´:
Password for ´https://github.com´:
remote: Repository not found.
fatal: repository ´https://github.com/thelinuxchoice/blackeye/´not found

Please help

**Comment by Zack-sys** [comment]
Thanks you for telling this error. The git clone was updated..... Here is the updated git clone (updated 2 days ago)

```
git clone https://github.com/Git-Ankitraj/blackeye-im.git
```
